### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhanghaidi** [maiqingqiang/newbee-mall-api-rs#1]
![image](https://github.com/maiqingqiang/newbee-mall-api-rs/assets/26913173/ec67f022-bdfa-46b8-be95-039678326ac3)

照着说明运行到cargo run 出现报错，系统win10 64位， rust版本1.71
cargo -V
cargo 1.71.0 (cfd3bbd8f 2023-06-08)

报错信息：
error: cannot find attribute `max_length` in this scope
   --> src\models\schema.rs:196:11
    |
196 |         #[max_length = 32]
    |           ^^^^^^^^^^

**Comment by johnmai-dev** [comment]
因为你安装 diesel_cli 版本太高了，跟代码中的diesel不一致，所以就报错了
https://github.com/diesel-rs/diesel/issues/3788

你现在可以clone最新代码，已经更新到diesel最新版本。 
https://github.com/maiqingqiang/newbee-mall-api-rs/commit/ea42fc80143639c6c5995aefa22e690ffa9ea411
https://github.com/maiqingqiang/newbee-mall-api-rs/commit/8d45b42566a7be96f94b7e0d5bfc3aa7989d79e6
